### ISSUE TITLE
Smoothing doesn't take effect

### ISSUE THREAD

**Issue by dmd** [miykael/3dprintyourbrain#12]
In two places you say to apply smoothing, but then to save it back to STL. That seems to have no effect - if you open up the saved STL file, it's back to the way it was.

Googling found: https://stackoverflow.com/questions/56906708/meshlab-how-to-fix-mesh-smoothing-not-saving-in-stl-file

**Comment by dmd** [comment]
Smoothing, saving to a `.ply`, loading that, then saving to a `.stl` seemed to do the trick.

**Comment by miykael** [comment]
Thanks for this input. In my case this worked. However, it was important to click on "File" and "Export Mesh" and overwrite the current file.
