### ISSUE TITLE
Will this work with only an image sequence?

### ISSUE THREAD

**Issue by AdamMarciniak** [miykael/3dprintyourbrain#13]
I don't have a DICOM image or a NIFTI file.
Will this work with just a seqeunce of images?

**Comment by miykael** [comment]
The code is setup in such a way that it expects an anatomical brain image. The DICOM or NIFTI file entry is not a requirement, but is just the most often used. If you have a sequence of images that you can prepare in such a way that it works with FreeSurfer's recon-all routine than you should be good to go.
