### ISSUE TITLE
Adapted script to work with WSL (windows subsystem for linux)

### ISSUE THREAD

**Issue by skjerns** [miykael/3dprintyourbrain#16]
Hey, just wanted to let you know that I adapted the script&instructions to work with WSL, so you can also run it if you're on a Windows machine. Also updated some of the commands to work well with recent versions of freesurfer&meshlab. Also added a stand, so you can easily connect it and make look pretty for your desk. I included everything in one script, so theoreticall you should be able to run the script out of the box and recieve a smoothed and ready 3D brain in the end without too much manual interference.

https://github.com/skjerns/3dprintyourbrain

Thanks a lot for your efforts, I already printed like 10 brains for participants.

**Comment by miykael** [comment]
Thank you for the pointer, I've added it with this commit https://github.com/miykael/3dprintyourbrain/commit/1c790efbf65b06297b4032b3208d16595d1de395. And you're printed brains look awesome!
