### ISSUE TITLE
concatenation

### ISSUE THREAD

**Issue by oricon** [miykael/3dprintyourbrain#2]
Thanks for tutorial - I'm having trouble merging cortical.stl and subcortical.stl:

```
echo 'solid '$EXPERIMENT_DIR'/final.stl' > $EXPERIMENT_DIR/final.stl
sed '/solid vcg/d' $EXPERIMENT_DIR/cortical.stl >> $EXPERIMENT_DIR/final.stl
sed '/solid vcg/d' $EXPERIMENT_DIR/subcortical.stl >> $EXPERIMENT_DIR/final.stl
echo 'endsolid '$EXPERIMENT_DIR'/final.stl' >> $EXPERIMENT_DIR/final.stl
```

Gives me the error:

> sed: RE error: illegal byte sequence

Are solid and endsolid meshlab commands? I don't see them in the meshlab folder (I'm on a mac).

Thanks!
Joe

**Comment by miykael** [comment]
I don't thinik that ``solid`` and ``endsolid`` are meshlab commands. But rather that they are needed in the stl-file to signal where the definition of a solid starts and end, similar to html `<body>` and `</body>`.

If you look into the stl file, you see something like this:
```
solid ./lh.pial.stl
facet normal 0.123619 -0.982447 0.139701
  outer loop
    vertex -13.502611 -103.938751 -8.596045
    vertex -14.001350 -104.040939 -8.873357
    vertex -13.292440 -104.007103 -9.262708
  endloop
endfacet
...
facet normal -0.120215 0.989334 0.082259
  outer loop
    vertex -8.405227 77.505745 12.792157
    vertex -8.481484 77.430939 13.580412
    vertex -7.844289 77.539787 13.202491
  endloop
endfacet
endsolid ./lh.pial.stl
```

**Comment by oricon** [comment]
Thanks, looks like it was an issue with sed on mac. I used GNU sed and it
worked.

--
Joseph M. Orr, Ph.D.
Assistant Professor
Department of Psychological and Brain Sciences
Texas A&M Institute for Neuroscience
Texas A&M University
College Station, TX
