### ISSUE TITLE
FSLMaths

### ISSUE THREAD

**Issue by Pezmc** [miykael/3dprintyourbrain#8]
The dependencies are listed as FreeSurfer and meshlab, but you also make use of `fslmaths`, which I believe is part of [FSL](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki) from the FMRIB Software Library?

Before I create a PR to add `FSL` installation to the readme, is my understanding correct? Or does `fslmaths` come from somewhere else?

**Comment by miykael** [comment]
You're completly right, @Pezmc! My mistake, I completely overlooked this. Would you mind adding [FSL](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki)?
