### ISSUE TITLE
Issue starting

### ISSUE THREAD

**Issue by tjop92** [miykael/3dprintyourbrain#9]
I am very unfamiliar with Linux and am trying to figure out how to complete Step 1.  I get the zip downloaded and unpacked.  But how do I do the following commands?  Or is this setting up folders?

Or is it easier using the script?  The only problem is that I have no idea how to run that script.  Could you help me figure out how to run it?

"Step 1 - Specify Variables

Let's first specify all necessary variables that we need for this to work:

# Main folder for the whole project
export EXPERIMENT_DIR=/users/mnotter/3dbrain

# Path to the FreeSurfer folder
export SUBJECTS_DIR=$EXPERIMENT_DIR/freesurfer

# Name of the subject
export subject=sub001

# Path to the structural image
export subjT1=$EXPERIMENT_DIR/${subject}/struct.nii.gz"

**Comment by miykael** [comment]
@tjop92 - one of the prerequisites for the scripts is the software [FreeSurfer](https://surfer.nmr.mgh.harvard.edu/), which is only available for Linux or OSX. There are some workarounds for Windows, e.g. using a virtual machine or something called [Docker](https://www.docker.com/). Once you have everything setup up and are good to go, you need to run a FreeSurfer algorithm, called `recon-all` for about 8-12h (4h on a powerful machine, using multicores).

If you want to learn how to do this, I'm happy to help you to set everything up. But if you want (and trust me :-)), you can also send me your MRI image and I can create the 3D model for you. Both options are fine for me.

**Comment by BynariStar** [comment]
I've had good luck running [3Dprinting_brain.sh](https://github.com/miykael/3dprintyourbrain/blob/master/script/3Dprinting_brain.sh) through WSL on Windows 10, just made a couple changes like sourcing FreeSurfer within the script instead of in .bashrc, and running MeshLab with xvfb due to the lack of a native X server.

It should be pretty simple to create an install script too (not including acquiring a FreeSurfer license).
Perhaps that would be useful?

**Comment by tjop92** [comment]
@miykael 
What would be a good email address for you?  Or I can give you mine.  I have the data in a google drive.

Honestly, I want what would be easier for you.  I have basically no experience with linux, and am having issues just getting freesurfer installed.  So I would imagine that it would take a lot of time and work to get it working on for me.  Please let me know what would be best for you.  :)

**Comment by miykael** [comment]
@BynariStar, that's cool. I didn't know about WSL. Does that mean you don't need a dual boot or virtual machine / docker to directly run some linux code on Windows? If you have time and energy, would be a great addition to have such a script as well.

**Comment by miykael** [comment]
@tjop92 - the best way to reach me is under michaelnotter@hotmail.com. For me, the easiest solution is to create the model for you. So, if you just want your 3D model, no problem, send me your brain.

But if you want to figure out how all of this works, don't hesitate. I'm happy to guide you through linux, FreeSurfer etc.
